fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive.git"
      ref:  "v1.3.0"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    java: "git://github.com/puppetlabs/puppetlabs-java"
  symlinks:
    druid: "#{source_dir}"
